# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_input'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='stock',
        ),
    ]
