# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
    ]
