# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180114_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('debit', models.CharField(max_length=10)),
                ('credit', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
