# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Qual o nome da sua empresa', max_length=200)),
                ('mail', models.EmailField(help_text='Qual o seu e-mail?', max_length=200)),
                ('reason', models.CharField(help_text='Qual o principal motivo de voce utilizar nossos serviços?', max_length=100)),
                ('cnpj', models.CharField(help_text='Digite com pontos e barra, exemplo 000.000.000/0000-00', max_length=18)),
                ('lifetime', models.CharField(help_text='Quanto tempo de vida tem sua empresa?', max_length=20)),
                ('funcionarios', models.CharField(help_text='Quantos funcionarios voce tem?', max_length=20)),
                ('socios', models.CharField(help_text='Qual o nome do principal socio?', max_length=50)),
                ('cpf', models.CharField(help_text='Qual o CPF do principal socio, preencha com pontos e barra', max_length=14)),
            ],
        ),
    ]
