# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_myplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplan',
            name='cnpj',
            field=models.CharField(help_text='Digite com pontos e barra, exemplo 000.000.000/0000-00', max_length=19),
        ),
    ]
