# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20180311_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplan',
            name='motivo',
            field=models.CharField(help_text='Resumidamente diga como nos conheceu?', max_length=40),
        ),
    ]
