# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20180311_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplan',
            name='confirmacao_do_plano',
            field=models.CharField(choices=[('STARTUP', 'Startup, apenas R$ 19,90 mensais!'), ('Business', 'Business, Apenas R$ 199,00 mensais!'), ('Corporate', 'Corporate, Um preço especial, uma super oferta no seu e-mail!')], max_length=10),
        ),
    ]
