# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20180311_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECD01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REG', models.CharField(choices=[('0000', '0000')], max_length=4)),
                ('LECD', models.CharField(choices=[('LECD', 'LECD')], max_length=4)),
                ('DT_INI', models.DateTimeField()),
                ('DT_FIN', models.DateTimeField()),
                ('Nome_da_Empresa', models.CharField(help_text='Qual o nome da sua empresa', max_length=200)),
                ('CNPJ', models.CharField(help_text='Qual o CNPJ ', max_length=14)),
                ('UF', models.EmailField(help_text='Qual a sua UF', max_length=2)),
                ('IM', models.CharField(help_text='Qual a sua inscricao municipal', max_length=40)),
                ('IN_SIT_ESP', models.CharField(help_text='SITUACAO ESPECIAL, SIM OU NAO? (S OU N)', max_length=1)),
                ('IND_SIT_INI_PER', models.CharField(help_text='SITUACAO ESPECIAL, SIM OU NAO? (S OU N)', max_length=1)),
                ('IND_NIRE', models.CharField(help_text='POSSUI NIRE, NAO OU SIM (0 OU 1)', max_length=1)),
                ('IND_FIN_ESC', models.CharField(help_text='ESCRITURACAO ORIGINAL OU SUBSTITUTA? (0 - ORIGINAL E 1 - SUBSTITUTA)', max_length=1)),
                ('COD_HASH_SUB', models.CharField(help_text='CODIGO DO HASH ANTERIOR', max_length=40)),
                ('IND_GRANDE_PORTE', models.CharField(help_text='Empresa de grande porte 1 ou de pequeno porte 0', max_length=1)),
                ('TIP_ECD', models.CharField(help_text='Indicador do tipo de ECD: 0 – ECD de empresa não participante de SCP como sócio ostensivo, 1 – ECD de empresa participante de SCP como sócio ostensivo, 2 – ECD da SCP', max_length=1)),
                ('COD_SCP', models.CharField(blank=True, max_length=14)),
                ('IDENT_MF', models.CharField(choices=[('S', 'S'), ('N', 'N')], help_text='S caso utilize moeda funcional', max_length=1)),
                ('IND_ESC_CONS', models.CharField(choices=[('S', 'S'), ('N', 'N')], help_text='Caso a contabilidade seja consolidada na controladroa', max_length=1)),
            ],
        ),
    ]
