# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20180318_0026'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ecd01',
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='ecd01',
            name='CLOSING',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='ecd01',
            name='INITIAL',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='ecd01',
            name='COD_HASH_SUB',
            field=models.CharField(blank=True, help_text='CODIGO DO HASH ANTERIOR', max_length=40),
        ),
        migrations.AlterField(
            model_name='ecd01',
            name='DT_FIN',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ecd01',
            name='DT_INI',
            field=models.DateField(),
        ),
    ]
