# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20180318_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecd01',
            name='DT_FIN',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ecd01',
            name='DT_INI',
            field=models.DateField(),
        ),
    ]
