# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20180318_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecd01',
            name='CLOSING',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='ecd01',
            name='INITIAL',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
