# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20180318_0339'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounting',
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='accounting',
            name='date',
            field=models.DateField(),
        ),
    ]
