# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20180319_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='Segmento',
            field=models.CharField(choices=[('SERVIÇOS', 'SERVIÇOS'), ('INDUSTRIA', 'INDUSTRIA'), ('COMÉRCIO', 'COMÉRCIO'), ('AGRONEGÓCIO', 'AGRONEGÓCIO'), ('STARTUP', 'STARTUP')], help_text='Insira seu segmento', max_length=12),
        ),
    ]
