# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20180319_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNPJ', models.CharField(help_text='Qual o CNPJ sem pontos ou barras ?', max_length=14)),
                ('Nome_da_Empresa', models.CharField(help_text='Qual o nome da sua empresa?', max_length=200)),
                ('email', models.EmailField(help_text='Qual o seu e-mail?', max_length=200)),
                ('Seu_nome', models.CharField(help_text='Qual o seu nome?', max_length=200)),
                ('Seu_cargo', models.CharField(help_text='Qual o seu cargo?', max_length=200)),
                ('Segmento', models.CharField(choices=[('SERVIÇOS', 'SERVIÇOS'), ('INDUSTRIA', 'INDUSTRIA'), ('COMÉRCIO', 'COMÉRCIO'), ('AGRONEGÓCIO', 'AGRONEGÓCIO'), ('STARTUP', 'STARTUP')], help_text='Insira seu segmento', max_length=12)),
                ('Faturamento_Ultimo_Mes', models.FloatField(blank=True, default=None, help_text='Insira o faturamento Liquido sem impostos', null=True)),
                ('Faturamento_Penultimo_Mes', models.FloatField(blank=True, default=None, help_text='Insira o faturamento Liquido sem impostos', null=True)),
                ('Faturamento_Antepenultimo_mes', models.FloatField(blank=True, default=None, help_text='Insira o faturamento Liquido sem impostos', null=True)),
                ('Despesas_Ultimo_Mes', models.FloatField(blank=True, default=None, help_text='Insira as despesas totais sem impostos', null=True)),
                ('Despesas_Penultimo_Mes', models.FloatField(blank=True, default=None, help_text='Insira as despesas totais sem impostos', null=True)),
                ('Despesas_Antepenultimo_Mes', models.FloatField(blank=True, default=None, help_text='Insira as despesas totais sem impostos', null=True)),
            ],
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Value', models.FloatField(blank=True, default=None, null=True)),
            ],
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
