# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_data_dolar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
