# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_delete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolar',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
