# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20180319_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dolar',
        ),
    ]
