# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='Dicas',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], help_text='Gostaria de receber dicas de Investimento?', max_length=12),
        ),
    ]
