# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20180320_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplan',
            name='confirmacao_do_plano',
            field=models.CharField(choices=[('STARTUP', 'Startup, apenas R$ 49,90 mensais!'), ('Business', 'Business, Apenas R$ 199,00 mensais!'), ('Corporate', 'Corporate, Um preço especial, uma super oferta no seu e-mail!')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='Asset',
            field=models.CharField(help_text='Qual o ativo voce quer analisar? Exemplo: petr4 para analisar Petrobras', max_length=10),
        ),
    ]
