# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20180328_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='amount',
            field=models.FloatField(),
        ),
    ]
