# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20180329_0023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounting',
            unique_together=set([('history', 'amount', 'date')]),
        ),
    ]
