# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20180411_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='data_carteira',
            field=models.DateField(verbose_name=['%d/%m/%Y']),
        ),
    ]
