# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20180411_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Data_Chegada_Brasil',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Data_Opção_FGTS',
            field=models.DateField(blank=True, help_text='Mesma data da admissão', null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Defeitos',
            field=models.CharField(blank=True, help_text='Caso aplicavel', max_length=12),
        ),
        migrations.AlterField(
            model_name='employees',
            name='N_Carteira_Mod_19',
            field=models.CharField(blank=True, help_text='No caso de estrageiro, informar o numero', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Validade_Cart_Identidade_Estrangeiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Validade_Carteira_Trabalho',
            field=models.DateField(blank=True, null=True),
        ),
    ]
