# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
